name: Deploy Backend to Elastic Beanstalk

on:
  push:
    branches: [ "main" ] # Triggers on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Your AWS region

      - name: Generate deployment package
        run: zip -r deploy.zip . -x ".git/*" "node_modules/*" ".github/*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: mom-app
          environment_name: Mom-app-env # Name of your EB environment
          region: ap-south-1
          version_label: "v1-${{ github.sha }}"
          deployment_package: deploy.zip